name: READMEUPDATER

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:

  update:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: Edit the README.md
        if: github.event.pull_request.merged == true
        run: |
              python scripts/updater.py
              git add README.md
              git commit -m "Auto update to README.md"
              git fetch origin master
              git push origin HEAD:master
        env:
          repo: ${{github.event.pull_request.base.repo.name}}
          assignees: ${{github.event.pull_request.assignees}}

